name: Update Kaggle Stats

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch: # Manual trigger

jobs:
  update-kaggle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Kaggle API
        run: pip install kaggle matplotlib

      - name: Create Kaggle config
        run: |
          mkdir -p ~/.kaggle
          echo '{"username":"anadiskt","key":"b485f80ad71307a1d0e2447573005104"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Generate Kaggle Activity Card
        run: python scripts/kaggle_card.py

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update Kaggle stats'
          file_pattern: 'README.md kaggle.png'
